org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

mod_version=0.14.5-3

mod_id=dscombat
mod_name=Diamond Star Combat
mod_license=MIT
mod_authors=1whohears
mod_description=A vehicle warfare mod that adds planes, tanks, and boats. Use radars to lock onto enemies and shoot them with radar guided missiles.

maven_group=com.onewhohears.dscombat
archives_name=dscombat
enabled_platforms = fabric,forge

homepage=https://github.com/1whohears
sources=https://github.com/1whohears/DiamondStarCombat
issue_tracker=https://github.com/1whohears/DiamondStarCombat/issues

minecraft_version=1.20.1
minecraft_version_range=[1.20.1)

architectury_version = 9.2.14

fabric_loader_version = 0.17.2
fabric_api_version = 0.92.6+1.20.1

forge_version = 1.20.1-47.4.0
forge_version_range=[47,)
forge_loader_version_range=[47,)

jei_version = 15.20.0.112
onewholibs_version=2.2.0
minigames_version = 0.5.0
distant_players_version = 0.3.7
tacticalviewer_version = 0.5.0

xaeros_minimap_fair_play_version = 24.2.0
xaeros_minimap_fair_play_id_forge = 5548212
xaeros_minimap_fair_play_id_fabric = 5548207

tacz_version = 1.1.6
tacz_id_forge = 6654541

forgeconfigapiport_version = 8.0.2

modernfix_version = 5.24.4
modernfix_forge_id = 6837713
modernfix_fabric_id = 6837712

distanthorizons_api_version=5.1.0
distanthorizons_version=2.4.5-b-1.20.1