modLoader="javafml"
loaderVersion="[41,43)"
license="MIT License"
issueTrackerURL="https://github.com/1whohears/DiamondStarCombat/issues"
showAsResourcePack=false

[[mods]]
	modId="dscombat"
	version="${file.jarVersion}"
	displayName="Diamond Star Combat"
	logoFile="dscombat.png"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/diamond-star-combat"
	updateJSONURL="https://raw.githubusercontent.com/1whohears/ModVersions/main/DiamondStarCombat/update.json"
	displayTest = "MATCH_VERSION"
	authors="1whohears"
	credits="My Lizard"
	description="A vehicle combat mod that adds Planes, Helicoptors, Tanks, Radars, Missiles and more!"

[[dependencies.dscombat]]
    modId="forge"
    mandatory=true
    versionRange="[41,43)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dscombat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.19.2)"
    ordering="NONE"
    side="BOTH"
