modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory
license="MIT License"

[[mods]] #mandatory

modId="dscombat" #mandatory
version=${file.jarVersion} #mandatory
displayName="Diamond Star Combat" #mandatory
#logoFile="dscombat.png" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/diamond-star-combat" #optional
updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/diamond-star-combat/files" #optional
issueTrackerURL="https://github.com/1whohears/DiamondStarCombat/issues" #optional
authors="1whohears" #optional
credits="" #optional
description="A vehicle combat mod that adds Planes, Helicoptors, Tanks, Radars, Missiles and more!"

[[dependencies.dscombat]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.dscombat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
