import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    id "com.gradleup.shadow"
}

architectury {
    common rootProject.enabled_platforms.split(',')
}

loom {
    accessWidenerPath = file("src/main/resources/dscombat.accesswidener")
}

dependencies {
    modApi "dev.architectury:architectury:${rootProject.architectury_version}"

    modApi "com.onewhohears.onewholibs:onewholibs-common-${rootProject.minecraft_version}:${rootProject.onewholibs_version}"
    modApi "com.onewhohears.minigames:minigames-common-${rootProject.minecraft_version}:${rootProject.minigames_version}"
    modApi "com.onewhohears.distant_players:distant_players-common-${rootProject.minecraft_version}:${rootProject.distant_players_version}"
}

tasks.register("commonShadowJar", ShadowJar) {
    archiveClassifier.set("shadowed")

    configurations = [project.configurations.shadowImpl]
}

configurations {
    shadowedElements {
        canBeConsumed = true
        canBeResolved = false
    }
    shadowImpl {
        canBeResolved = true
        canBeConsumed = false
        extendsFrom implementation
    }
}

artifacts {
    shadowedElements tasks.named("commonShadowJar")
}

sourceSets {
    main {
        resources {
            srcDir 'src/generated/resources'
        }
    }
}